name: optics-si-cloud
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - matplotlib
  - folium
  - bokeh
  - plotly
  - Pillow
  - sphinx-revealjs
  - sphinxcontrib-mermaid
  - pip
  - pip:
      - "jupyter-book<2"
      - ghp-import
      - requests